modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
    modId="card_collections"
    version="${file.jarVersion}"
    displayName="Card Collections"
    # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
    logoFile="examplemod.png" #optional
    credits="Thanks for this example mod goes to Java" #optional
    authors="skydarkchen"
    description='''
    This is a long form description of the mod. You can write whatever you want here

    Have some lorem ipsum.

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis lacinia magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sagittis luctus odio eu tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque volutpat ligula eget lacus auctor sagittis. In hac habitasse platea dictumst. Nunc gravida elit vitae sem vehicula efficitur. Donec mattis ipsum et arcu lobortis, eleifend sagittis sem rutrum. Cras pharetra quam eget posuere fermentum. Sed id tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    '''
[[dependencies.card_collections]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.card_collections]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
